# Generated by Django 6.0.1 on 2026-01-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_profession'),
        ('users', '0002_alter_user_cohort_alter_user_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='professions',
            field=models.ManyToManyField(blank=True, to='organisation.profession'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
