# Generated by Django 6.0.1 on 2026-01-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_profession_user_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='side_hustle',
            field=models.TextField(blank=True),
        ),
    ]
