# Generated by Django 6.0.1 on 2026-01-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_committee'),
        ('users', '0004_user_side_hustle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='professions',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.profession'),
        ),
    ]
