# Generated by Django 6.0.1 on 2026-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_professions_user_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='side_hustle',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_account',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_account',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='x_account',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_account',
            field=models.URLField(blank=True),
        ),
    ]
