# Generated by Django 6.0.1 on 2026-01-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_side_hustle_user_facebook_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biography',
        ),
    ]
