# Generated by Django 6.0.1 on 2026-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='years_at_mwiri_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_at_mwiri_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
