# Generated by Django 6.0.1 on 2026-06-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_years_at_mwiri_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='s4_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='s6_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
