# Generated by Django 6.0.1 on 2026-06-16 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideHustle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(help_text='Maximum 50 words.', max_length=500)),
                ('address', models.CharField(max_length=255)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='side_hustles/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='side_hustles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_hustles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
