# Generated by Django 6.0.1 on 2026-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosrequest',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
