# Generated by Django 6.0.1 on 2026-01-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DidYouKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateField()),
                ('description_of_event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_1_image', models.ImageField(upload_to='fixture_images/')),
                ('cohort_1_name', models.CharField(max_length=255)),
                ('cohort_2_image', models.ImageField(upload_to='fixture_images/')),
                ('cohort_2_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slider/')),
                ('hero_text', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
            ],
        ),
    ]
