# Generated by Django 6.0.1 on 2026-01-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManOfTheHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hero_image', models.ImageField(upload_to='man_of_the_hour/')),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='DidYouKnow',
        ),
    ]
