# Generated by Django 6.0.1 on 2026-01-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='legacy_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
