# Generated by Django 6.0.1 on 2026-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='additional_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
