# Generated by Django 6.0.1 on 2026-02-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('upcoming', 'Upcoming Events'), ('community', 'Community Impact')], max_length=32)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional override title; if blank the article title is used', max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='updates/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Featured News',
                'verbose_name_plural': 'Featured News',
                'ordering': ['order'],
            },
        ),
    ]
