# Generated by Django 6.0.1 on 2026-01-31 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_gallery_category_alter_history_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.AddField(
            model_name='history',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='history_images/'),
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='history_images/')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='content.history')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='content.news')),
            ],
        ),
    ]
