# Generated by Django 6.0.1 on 2026-09-02 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_history_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='history_pdfs/'),
        ),
        migrations.AlterField(
            model_name='history',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
