# Generated by Django 6.0.1 on 2026-09-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_history_pdf_file_alter_history_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('MARKETPLACE', 'Marketplace'), ('NEWS', 'News'), ('HISTORY', 'History')], default='NEWS', max_length=20),
        ),
    ]
