# Generated by Django 6.0.1 on 2026-01-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_image_product_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
