# Generated by Django 6.0.1 on 2026-01-30 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_gallery_category_alter_history_category_and_more'),
        ('products', '0003_remove_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='content.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
